name: django-simple-deploy CI tests

on:
  pull_request:

  push:
    branches:
      - main
      - start_ci

  workflow_dispatch:

jobs:
  test:
    name: Run tests on ${{ matrix.os }} with Python ${{ matrix.python-version}}
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest] #[ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.12"] #["3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv on macOS and Linux
        if: startsWith(matrix.os, 'macos-') || startsWith(matrix.os, 'ubuntu-')
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install uv on Windows
        if: startsWith(matrix.os, 'windows-')
        run: |
          powershell -c "irm https://astral.sh/uv/install.ps1 | iex"

      - name: Install dependencies on macOS and Linux
        if: startsWith(matrix.os, 'macos-') || startsWith(matrix.os, 'ubuntu-')
        run: |
          uv venv .venv
          source .venv/bin/activate

          uv pip install -r requirements.txt
          uv pip install poetry
          git clone https://github.com/django-simple-deploy/dsd-flyio.git ../dsd-flyio
          uv pip install -e ../dsd-flyio

      - name: Install dependencies on Windows
        if: startsWith(matrix.os, 'windows-')
        run: |
          # uv venv .venv
          # .venv\Scripts\activate

          uv venv run uv pip install -r requirements.txt
          uv venv run uv pip install poetry
          git clone https://github.com/django-simple-deploy/dsd-flyio.git ..\dsd-flyio
          uv venv run uv pip install -e ..\dsd-flyio

      - name: Configure Git
        run: |
          git config --global user.email "ci_tester@example.com"
          git config --global user.name "Ci Tester"
          git config --global init.defaultBranch main

      - name: Run unit tests on macOS and Linux
        if: startsWith(matrix.os, 'macos-') || startsWith(matrix.os, 'ubuntu-')
        run: |
          source .venv/bin/activate
          pytest tests/unit_tests -x

      - name: Run integration tests on macOS and Linux
        if: startsWith(matrix.os, 'macos-') || startsWith(matrix.os, 'ubuntu-')
        run: |
          source .venv/bin/activate
          pytest tests/integration_tests -x

      - name: Run unit tests on Windows
        if: startsWith(matrix.os, 'windows-')
        run: |
          uv venv run pytest tests/unit_tests -x

      - name: Run integration tests on Windows
        if: startsWith(matrix.os, 'windows-')
        run: |
          uv venv run pytest tests/integration_tests -x
