name: django-simple-deploy CI tests

on:
  pull_request:

  push:
    branches:
      - main
      - start_ci

  workflow_dispatch:

jobs:
  test:
    name: Run tests on ${{ matrix.os }} with Python ${{ matrix.python-version}}
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest] #[ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11"] #["3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          # python -m pip install --upgrade pip
          uv pip install -r requirements.txt
          uv pip install poetry
          git clone https://github.com/django-simple-deploy/dsd-flyio.git ../dsd-flyio
          uv pip install -e ../dsd-flyio

          # Configure git.
          git config --global user.email "ci_tester@example.com"
          git config --global user.name "Ci Tester"
          git config --global init.defaultBranch main

      # Fly is used for CI testing.
      # - name: Install Fly.io CLI (Linux/macOS)
      #   if: startsWith(matrix.os, 'macos-') || startsWith(matrix.os, 'ubuntu-')
      #   uses: superfly/flyctl-actions/setup-flyctl@master
      # - name: Install Fly.io CLI (Windows)
      #   if: startsWith(matrix.os, 'windows-')
      #   run: |
      #     iwr https://fly.io/install.ps1 -useb | iex
      #     echo "$HOME/.fly/bin" >> $GITHUB_PATH
      # - name: Check Fly.io CLI installation
      #   run: |
      #     flyctl version

      - name: Run unit tests
        run: pytest tests/unit_tests -x

      - name: Run integration tests
        run: pytest tests/integration_tests -x
